config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # shortcut for all the routes for the passwords resource
  resources :passwords do
  # routes for password sharing btw users add a nested route
  resources :shares, only: [:new, :create, :destroy]
  # command rails routes -g shares to see all nested routes
      # password_shares GET  /passwords/:password_id/shares(.:format)   shares#index
      # POST   /passwords/:password_id/shares(.:format)  shares#create
      # new_password_share GET /passwords/:password_id/shares/new(.:format) shares#new
      # edit_password_share GET    /passwords/:password_id/shares/:id/edit(.:format) shares#edit
      # password_share GET    /passwords/:password_id/shares/:id(.:format) shares#show
      # PATCH  /passwords/:password_id/shares/:id(.:format)  shares#update
      # PUT    /passwords/:password_id/shares/:id(.:format)  shares#update
      # DELETE /passwords/:password_id/shares/:id(.:format) shares#destroy
  end
  


  # Defines the root path route ("/")
  root "passwords#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/password.rb
class Password < ApplicationRecord
  # A password can have many user_passwords (entries in the join table)
  # A password can belong to many users through the user_passwords join table
  has_many :user_passwords, dependent: :destroy
  has_many :users, through: :user_passwords

  encrypts :username, deterministic: true
  encrypts :password

  validates :url, presence: true
  validates :username, presence: true
  validates :password, presence: true

  def can_edit?(user)
    user_passwords.find_by(user: user)&.can_edit?(user)
  end

  def can_share?(user)
    user_passwords.find_by(user: user)&.shareable?
  end

  def can_delete?(user)
    user_passwords.find_by(user: user)&.deletable?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

#  A user has many passwords (one-to-many) through the user_passwords join table
#  A user can have many user_passwords (entries in the join table)

has_many :user_passwords, dependent: :destroy
has_many :passwords, through: :user_passwords
end

app/models/user_password.rb
class UserPassword < ApplicationRecord
  # This is the join table model that connects users and passwords -> allows for the many-to-many relationship between users and passwords
  # Each user_password record represents one user owning one password
  belongs_to :user
  belongs_to :password

  ROLES = ["viewer", "editor", "owner"]
  #  view can only view the password
  # editor can update the password
  # owner can view, edit and share the password
  validates :role, presence: true, inclusion: { in: ROLES }

  attribute :role, default: "viewer"

  def owner?
    role == "owner"
  end

  def viewer?
    role == "viewer"
  end

  def editor?
    role == "editor"
  end

  def can_edit?(user)
    owner? || editor?
  end

  def shareable?
    owner?
  end

  def deletable?
    owner?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/passwordsController.rb
class PasswordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_password, except: [:index, :new, :create]
  before_action :require_editor_access, only: [:edit, :update]
  before_action :require_owner_access, only: [:destroy]
  
  # using current_user to also look for current user's passwords and not other users' passwords
  def index
  
    # Use joins to get passwords through the user_passwords join table
    # This will fetch all passwords associated with the current user
    # through the many-to-many relationship
    @passwords = current_user.passwords.includes(:user_passwords)
  end

  def new
    @password = Password.new
  end

  def create
    # .create creates row with join table
    # @password = current_user.passwords.create(password_params)
    @password = Password.new(password_params)
    @password.user_passwords.new(user: current_user, role: "owner")
    if @password.save
      redirect_to @password
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end
  
  def edit
  end

  def update
    if @password.update(password_params)
      redirect_to @password
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # because of foreign key constraint, we need to destroy the join table row first
    @password.destroy
    redirect_to root_path
  end

  private
  def password_params
    params.require(:password).permit(:url, :username, :password)
  end

  def set_password
    @password = current_user.passwords.find(params[:id])
  end

  def require_editor_access
    redirect_ to @password unless @password.can_edit?(current_user)
  end

  def require_owner_access
    redirect_ to @password unless @password.can_share?(current_user)
  end
end

app/controllers/sharesController.rb
class SharesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_password
  
  
  def new
    @users = User.excluding(@password.users)
    @user_password = UserPassword.new
  end

  def create
    @user_password = @password.user_passwords.new(user_password_params)
    if @user_password.save
      redirect_to @password
    else
      @users = User.excluding(@password.users)
      render :new, status: :unprocessable_entity
    end 
  end

  def destroy
    @password.user_passwords.where(user_id: params[:id]).destroy_all
    redirect_to @password
  end
  

  private
  def set_password
    @password = current_user.passwords.find(params[:password_id])
  end

  def user_password_params
    params.require(:user_password).can_share?(:user_id, :role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Password Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="main-nav">
  <%= link_to "Home", root_path %>
  
  <% if user_signed_in? %>
    <%= link_to "All Passwords", passwords_path %>
    <%= link_to "Add New Password", new_password_path %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>
</nav>

    <div class="main-container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shares/new.html.erb
<h1>Share Password</h1>

<%= form_with model: [@password, @user_password], url: password_shares_path(@password) do |form| %>
  <div>
  <%= form.label :user_id %>
  <%= form.collection_select :user_id, @users, :id, :email %>
  </div>

  <div>
  <%= form.label :role %>
  <%= form.select :role, UserPassword::ROLES.map { |role| [role.titleize, role] } %>
  </div>

  <div>
  <%= form.submit "Share Password" %>
  </div>
  <% end %>